// ecdsa_fixture.mjs
//
// Regenerates circuits/zkfrank_test/src/fixture.nr: a college keypair plus
// signatures over the commitments the TXE tests use.
//
// The tests cannot sign anything themselves - Noir verifies signatures but
// cannot produce them, and TXE has no access to a private key. So the signing
// happens here, once, and the result is committed as Noir constants.
//
// The Node and Noir sides must agree on exactly which bytes get hashed:
// createSign('SHA256') hashes the message and signs the digest, while
// verify_signature does no hashing and takes the digest as an argument. A
// mismatch shows up only as "signature invalid", indistinguishable from a
// forgery, which is why this file spells the byte handling out.
//
// Usage: node scripts/ecdsa_fixture.mjs > circuits/zkfrank_test/src/fixture.nr
//
// Needs the @aztec packages on the module path, same as scripts/validate_demo.mjs.

import { poseidon2Hash } from '@aztec/foundation/crypto/poseidon';
import { generateSchoolKeys, signStudentData } from '../backend/src/crypto/ecdsa.js';

// The credentials the tests exercise. VALID is the card the college issues;
// WRONG_SECRET is a commitment the college would also sign but never registers,
// which is how a test can reach the registry check with a good signature.
const CREDENTIALS = [
    { name: 'VALID', studentId: 1001n, secret: 42n },
    { name: 'WRONG_SECRET', studentId: 1001n, secret: 99n },
];

// commitment = poseidon2([student_id, secret]), the same hash the contract
// computes inside validate().
async function commitmentOf({ studentId, secret }) {
    return (await poseidon2Hash([studentId, secret])).toBigInt();
}

// A Field serialized big-endian into 32 bytes - what Field::to_be_bytes()
// produces in the circuit, so both sides hash identical bytes.
function fieldBytes(value) {
    return Buffer.from(value.toString(16).padStart(64, '0'), 'hex');
}

// Format a buffer as a Noir array literal, wrapped so the output stays readable.
function noirArray(buffer) {
    const rows = [];
    const bytes = [...buffer];
    for (let i = 0; i < bytes.length; i += 12) {
        rows.push('    ' + bytes.slice(i, i + 12).join(', '));
    }
    return '[\n' + rows.join(',\n') + ',\n]';
}

const college = generateSchoolKeys();
// A second, unrelated issuer. Its signatures are well-formed and verify against
// its own key - they must still be rejected, because the contract only trusts
// the college key it was deployed with.
const impostor = generateSchoolKeys();

const lines = [];
lines.push('// Generated by scripts/ecdsa_fixture.mjs - do not edit by hand.');
lines.push('//');
lines.push('// The college keypair behind these signatures is ephemeral: it is generated');
lines.push('// fresh on every run and only its public half survives, here. Regenerating this');
lines.push('// file therefore invalidates every signature in it at once - which is fine,');
lines.push('// since they are all regenerated together.');
lines.push('');
lines.push(`pub global COLLEGE_PUBLIC_KEY_X: [u8; 32] = ${noirArray(Buffer.from(college.publicKey.x, 'base64url'))};`);
lines.push('');
lines.push(`pub global COLLEGE_PUBLIC_KEY_Y: [u8; 32] = ${noirArray(Buffer.from(college.publicKey.y, 'base64url'))};`);

for (const credential of CREDENTIALS) {
    const commitment = await commitmentOf(credential);
    const signature = signStudentData(college.privateKey, fieldBytes(commitment));

    lines.push('');
    lines.push(`// poseidon2([${credential.studentId}, ${credential.secret}])`);
    lines.push(`pub global ${credential.name}_COMMITMENT: Field = ${commitment};`);
    lines.push('');
    lines.push(`pub global ${credential.name}_SIGNATURE: [u8; 64] = ${noirArray(signature)};`);
}

// Same commitment as VALID, signed by the wrong issuer.
const validCommitment = await commitmentOf(CREDENTIALS[0]);
const impostorSignature = signStudentData(impostor.privateKey, fieldBytes(validCommitment));
lines.push('');
lines.push('// A structurally valid signature over the right commitment, made by an issuer');
lines.push('// the contract does not trust.');
lines.push(`pub global IMPOSTOR_SIGNATURE: [u8; 64] = ${noirArray(impostorSignature)};`);

process.stdout.write(lines.join('\n') + '\n');
