// ecdsa_fixture.mjs
//
// Generates a college keypair, signs a value the way the real issuer will, and
// prints the result as Noir literals ready to paste into a test.
//
// This exists because the Node and Noir sides must agree on exactly which bytes
// get hashed. Node's createSign('SHA256') hashes the message internally and
// signs the digest; Noir's verify_signature takes that digest as an argument and
// does no hashing of its own. If the two hash different bytes the only symptom
// is "signature invalid", with nothing to say which side is wrong. Pinning the
// handshake with a fixture makes the failure visible here instead.
//
// Usage: node scripts/ecdsa_fixture.mjs [decimal-field-value]

import { generateSchoolKeys, signStudentData } from '../backend/src/crypto/ecdsa.js';

// The value being signed. In production this is the commitment,
// poseidon2([student_id, secret]); any Field-sized number works for a fixture.
const value = BigInt(process.argv[2] ?? '123456789');

// A Field serialized big-endian into 32 bytes - the same thing Noir's
// Field::to_be_bytes() produces, so both sides hash identical bytes.
const message = Buffer.from(value.toString(16).padStart(64, '0'), 'hex');

const { publicKey, privateKey } = generateSchoolKeys();

// Sign the raw 32 bytes, NOT a hex or decimal string of them. This is the whole
// point of the fixture: "0x1234..." and the bytes 0x12 0x34 ... hash to
// completely different digests, and Noir only ever sees the bytes.
const signature = signStudentData(privateKey, message);

// A JWK carries the public key coordinates as base64url; Noir wants raw bytes.
const publicKeyX = Buffer.from(publicKey.x, 'base64url');
const publicKeyY = Buffer.from(publicKey.y, 'base64url');

// Format a buffer as a Noir array literal, wrapped so the output stays readable.
function noirArray(buffer) {
    const bytes = [...buffer].map((b) => String(b).padStart(3, ' '));
    const rows = [];
    for (let i = 0; i < bytes.length; i += 12) {
        rows.push('    ' + bytes.slice(i, i + 12).join(', '));
    }
    return '[\n' + rows.join(',\n') + ',\n]';
}

console.log('// Fixture generated by scripts/ecdsa_fixture.mjs - do not edit by hand.');
console.log(`// Signed value: ${value}`);
console.log();
console.log(`global VALUE: Field = ${value};`);
console.log();
console.log(`global PUBLIC_KEY_X: [u8; 32] = ${noirArray(publicKeyX)};`);
console.log();
console.log(`global PUBLIC_KEY_Y: [u8; 32] = ${noirArray(publicKeyY)};`);
console.log();
console.log(`global SIGNATURE: [u8; 64] = ${noirArray(signature)};`);

// Sanity checks, so a broken fixture never reaches Noir.
if (publicKeyX.length !== 32 || publicKeyY.length !== 32) {
    throw new Error(`public key must be 32+32 bytes, got ${publicKeyX.length}+${publicKeyY.length}`);
}
if (signature.length !== 64) {
    throw new Error(`signature must be 64 bytes, got ${signature.length}`);
}
